version: '3.7'

services:
#  crawloop-engine:
#    image: harbor.socmap.net/crawloop/crawloop-engine:v4.0.13
#    build:
#      context: ./services/engine
#      dockerfile: Dockerfile-prod
#    env_file:
#      - crawloop-engine-prod.env

  crawloop-spider:
    image: harbor.socmap.net/crawloop/crawloop-spider:v1.0.4
    build:
      context: ./services/spider
      dockerfile: Dockerfile-prod
    env_file:
      - crawloop-spider-prod.env

