version: '3.7'

services:
  engine:
    container_name: engine
    build:
      context: ./services/engine
      dockerfile: Dockerfile-dev
    volumes:
      - './services/engine:/usr/src/app'
    ports:
      - 15000:5000
    env_file:
      - engine.env
    environment:
      - FLASK_APP=webs:create_app
      - ENDPOINT=web
    restart: always

  engine-worker:
    container_name: engine-worker
    build:
      context: ./services/engine
      dockerfile: Dockerfile-dev
    volumes:
      - './services/engine:/usr/src/app'
    env_file:
      - engine.env
    environment:
      - ENDPOINT=engine-worker
    restart: always

  engine-grpc:
    container_name: engine-grpc
    build:
      context: ./services/engine
      dockerfile: Dockerfile-dev
    volumes:
      - './services/engine:/usr/src/app'
    ports:
      - 15002:15002
    env_file:
      - engine.env
    environment:
      - ENDPOINT=engine-grpc
    restart: always

engine-apscheduler:
  container_name: engine-apscheduler
  build:
    context: ./services/engine
    dockerfile: Dockerfile-dev
  volumes:
    - './services/engine:/usr/src/app'
  ports:
    - 15003:15003
  env_file:
    - engine.env
  environment:
    - ENDPOINT=apscheduler
  restart: always