version: '3.7'

services:
  spider-client:
    container_name: spider-client
    build:
      context: ./services/spider
      dockerfile: Dockerfile-dev
    volumes:
      - './services/spider:/usr/src/app'
    ports:
      - 15001:5000
    env_file:
      - spider.env
    environment:
      - FLASK_APP=webs:create_app
      - ENDPOINT=web
    restart: always

  spider-fetch:
    container_name: spider-fetch
    build:
      context: ./services/spider
      dockerfile: Dockerfile-dev
    volumes:
      - './services/spider:/usr/src/app'
    env_file:
      - spider.env
    environment:
      - ENDPOINT=fetch
    restart: always


  save-results:
    container_name: save-results
    build:
      context: ./services/spider
      dockerfile: Dockerfile-dev
    volumes:
      - './services/spider:/usr/src/app'
    env_file:
      - spider.env
    environment:
      - ENDPOINT=results
    restart: always